name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_SECRET }}
          config_display: columns
          plugin_lines: true
          base_hireable: true
          config_timezone: Europe/Paris
          plugin_achievements: true
          plugin_habits: true
          plugin_languages: true
          plugin_calendar: true
          
